### ISSUE TITLE
Cannot get working for arrival time

### ISSUE THREAD

**Issue by reidsneo** [BlinkTagInc/transit-arrivals-widget#9]
![image](https://user-images.githubusercontent.com/12298979/158557739-e0e9b815-96dc-4086-9cbe-0323f77315ab.png)

```

{
  "agency": {
    "agency_key": "youragency",
    "gtfs_static_url": "http://www.viainfo.net/BusService/google_transit.zip",
    "gtfs_rt_tripupdates_url": "tripupdates.pb"
  },
  "beautify": true,
  "locale": "en",
  "noHead": false,
  "refreshIntervalSeconds": 20,
  "templatePath": "views/widget",
  "timeFormat": "12hour",
  "sqlitePath": "gtfs"
}

```

**Comment by reidsneo** [comment]
![image](https://user-images.githubusercontent.com/12298979/158558270-4a93b3ca-d8f3-4585-9bb6-1aa64aec830f.png)

Update sometime is working but not always

**Comment by brendannee** [comment]
Thanks for reporting this.

I pushed an update that may solve the issue - check out the code on the master branch. If this solves your issue, I'll publish an updated release.

Is your GTFS-Realtime available on a public URL (I see you are running it against localhost:3000/tripupdates.pb)

**Comment by brendannee** [comment]
Thanks for the feedback.

Try the version 1.0.2 that I just released and let me know if that solves the issue.

**Comment by reidsneo** [comment]
Thank you, I think the problem is solved now

**Comment by brendannee** [comment]
Great.

Let me know if you end up implementing this anywhere and would like you agency listed in the readme as an example of agencies currently using this tool.
